Insert INTO CURRENCY_EXCHANGE ( ID , CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE , ENVIRONMENT )
ValUES
(10002,'USD','INR',65,'');

Insert INTO CURRENCY_EXCHANGE ( ID , CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE , ENVIRONMENT )
ValUES
(10003,'EUR','INR',66,'');

Insert INTO CURRENCY_EXCHANGE ( ID , CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE , ENVIRONMENT )
ValUES
(10004,'GBP','INR',67,'');